# Generated by Django 5.0.3 on 2024-03-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_rename_fotografias_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('GALAXIA', 'Galaxia'), ('ESTRELAS', 'Estrela'), ('CACHORRINHOS!', 'AUAU')], default='', max_length=100),
        ),
    ]
