# Generated by Django 5.0.3 on 2024-03-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotografias',
            new_name='Fotografia',
        ),
    ]
